version: '3.8'

services:
  backend:
    build:
      context: ../
      dockerfile: ./docker/Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - backend_data:/app/data
    depends_on:
      - db

  db:
    image: alpine/git
    command: sh -c "mkdir -p /data && touch /data/database.db && tail -f /dev/null"
    volumes:
      - backend_data:/data

volumes:
  backend_data:
